### PR TITLE
v3.2

### PR DESCRIPTION
**Pull request by patricksnape**
This will likely fail on Windows but should hopefully pass on OSX and Linux as it works locally for me.

### CODE REVIEW

**Comment by patricksnape** [comment]
@jabooth Jenkins is borked? condaci is missing and bill is offline?

**Comment by jabooth** [comment]
@patricksnape yeah Bill has fallen over, and the missing condaci front, euurgh yeah I know what that is.

**Comment by jabooth** [comment]
@patricksnape OK, both issues should now be fixed. You might need to re-run of course.

**Comment by patricksnape** [comment]
jenkins rebuild this please

**Comment by patricksnape** [comment]
jenkins retest this please

**Comment by raymondchua** [comment]
Any updates on this?

**Comment by patricksnape** [comment]
Please use conda-forge

**Pull request closed without merging**
